"use client";
import { useState } from "react"; import { Mail, Phone, MessageCircle, MapPin, ChevronDown, Send, CheckCircle2 } from "lucide-react"; import { Title } from "@/components/Shell";
const info = [[Mail, "Email", "support@capacityconnect.in"], [Phone, "Helpline", "1800-123-456 (toll free)"], [MessageCircle, "Live chat", "Mon to Sat, 9 AM to 6 PM IST"], [MapPin, "Office", "Capacity Building Cell, New Delhi 110001"]] as const;
const faqs = [["How do I reset my password?", "Use Forgot password on the login page. A reset link is sent to your registered email."], ["How do I verify a certificate?", "Open Certificates and select Verify. Employers can use the certificate ID the same way."], ["Can I retake an assessment?", "Yes. Select Retake on the result screen. Your best score is kept."], ["How are trainers matched to courses?", "Competency Matching compares required skill levels with each trainer's profile."]];
export default function Support() {
  const [open, setOpen] = useState<number | null>(0); const [sent, setSent] = useState(false);
  return (<><Title t="Support" s="We usually reply within one working day." />
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{info.map(([I, l, v]) => <div key={l} className="card pop"><I className="mb-3 text-indigo-600" /><p className="text-sm text-slate-500">{l}</p><p className="font-semibold">{v}</p></div>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2">
      <div className="card"><h2 className="mb-4 font-bold">Frequently asked questions</h2>{faqs.map(([q, a], i) => <div key={q} className="border-b last:border-0"><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between py-3.5 text-left text-sm font-semibold">{q}<ChevronDown size={18} className={`transition ${open === i ? "rotate-180" : ""}`} /></button>{open === i && <p className="pop pb-4 text-sm text-slate-500">{a}</p>}</div>)}</div>
      <div className="card"><h2 className="mb-4 font-bold">Send us a message</h2>
        {sent ? <div className="pop grid place-items-center py-10 text-center"><CheckCircle2 size={44} className="text-emerald-500" /><p className="mt-3 font-bold">Message sent</p><p className="text-sm text-slate-500">We will get back to you within one working day.</p><button className="btn2 mt-5" onClick={() => setSent(false)}>Send another</button></div> :
        <div className="space-y-3"><input placeholder="Your name" className="w-full rounded-xl border px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-indigo-400" /><input placeholder="Email address" className="w-full rounded-xl border px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-indigo-400" /><textarea rows={4} placeholder="How can we help?" className="w-full rounded-xl border px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-indigo-400" /><button className="btn w-full" onClick={() => setSent(true)}><Send size={16} />Send message</button></div>}</div></div></>);
}
